# Site settings
title: http://lahdensiniset.net
description: > # this means to ignore newlines until "baseurl:"
  Vire on Partiolippukunta Lahden Sinisten vuoden 2015 kesäleiri.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lahdensiniset.github.io" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
markdown: kramdown
permalink: pretty